cogPosDynamic:
- 0.231
- 0.671
- 0.565
cogPosDynamicRel:
- 0.002
- 0.164
- 0.654
cogPosStatic:
- 0.231
- 0.66
- 0.554
cogPosStaticRel:
- 0.231
- 0.674
- 0.261
cogToFrontAxle: 1.458
cogToLeftWheelAxle: 0.898
cogToRearAxle: 1.136
cogToRightWheelAxle: 0.902
distFR: 2.582
distLR: 1.826
inertia:
  xx: 335.729
  xy: -0.379
  xz: -15.992
  yy: 1163.275
  yz: 0.653
  zz: 1312.972
refNodePos:
- -0.0
- -0.014
- 0.293
totalMass: 851.18
vectorForward:
- 0.0
- -1.0
- 0.0
vectorLeft:
- 1.0
- 0.0
- 0.0
vectorUp:
- 0.0
- 0.0
- 1.0
vehHeight: 1.62
vehLength: 3.615
vehWidth: 1.835
wheel_fl:
  inertia: 0.605
  mass: 14.4
  pos:
  - 0.898
  - -1.458
  - -0.269
  radius: 0.395
  width: 0.225
wheel_fr:
  inertia: 0.605
  mass: 14.4
  pos:
  - -0.902
  - -1.458
  - -0.269
  radius: 0.395
  width: 0.225
wheel_rl:
  inertia: 0.605
  mass: 14.4
  pos:
  - 0.898
  - 1.136
  - -0.253
  radius: 0.395
  width: 0.225
wheel_rr:
  inertia: 0.605
  mass: 14.4
  pos:
  - -0.902
  - 1.136
  - -0.253
  radius: 0.395
  width: 0.225
engine:
  fuelCapacity: 25.0
  fuelVolume: 24.959
  idleRPM: 1400.0
  maxRPM: 8000.0
  superchargerBoostMax: -1.0
  turboBoostMax: 20.6
gearbox:
  R:
    index: -1
    mode_index: 0.4
    gear_ratio: 3.5
    mode: reverse
    indexCmd: -1
  N:
    index: 0
    mode_index: 0.55
    gear_ratio: 3.5
    mode: neutral
    indexCmd: 0
  P:
    index: 0
    mode_index: 0.0
    gear_ratio: 3.5
    mode: park
    indexCmd: 1
  D:
    index: 1
    mode_index: 0.78
    gear_ratio: 3.5
    mode: drive
    indexCmd: 2
powertrain:
  mainEngine:
    type: combustionEngine
    clutch:
      type: centrifugalClutch
      gearRatio: 1.0
      gearbox:
        type: cvtGearbox
        gearRatio: 3.5
        rangebox:
          type: rangeBox
          gearRatio: 2.23
          gearRatios:
            0.0: 2.23
            1.0: 4.56
          availableModes:
          - high
          - low
          transfercase:
            type: differential
            gearRatio: 1.0
            availableModes:
            - locked
            diffTorqueSplit: 0.5
            differential_R:
              type: differential
              gearRatio: 3.82
              availableModes:
              - locked
              diffTorqueSplit: 0.5
              wheelaxleRL:
                type: shaft
                gearRatio: 1.0
                availableModes:
                - connected
                spindleRL:
                  type: shaft
                  gearRatio: 1.0
                  availableModes:
                  - connected
              wheelaxleRR:
                type: shaft
                gearRatio: 1.0
                availableModes:
                - connected
                spindleRR:
                  type: shaft
                  gearRatio: 1.0
                  availableModes:
                  - connected
            torsionReactorF:
              type: torsionReactor
              gearRatio: 3.82
              driveshaft:
                type: shaft
                gearRatio: 1.0
                availableModes:
                - connected
                - disconnected
                differential_F:
                  type: differential
                  gearRatio: 1.0
                  availableModes:
                  - viscous
                  - locked
                  diffTorqueSplit: 0.5
                  wheelaxleFL:
                    type: shaft
                    gearRatio: 1.0
                    availableModes:
                    - connected
                    spindleFL:
                      type: shaft
                      gearRatio: 1.0
                      availableModes:
                      - connected
                  wheelaxleFR:
                    type: shaft
                    gearRatio: 1.0
                    availableModes:
                    - connected
                    spindleFR:
                      type: shaft
                      gearRatio: 1.0
                      availableModes:
                      - connected
controllers:
  4wd: 4wd
  doorLCoupler: advancedCouplerControl
  doorRCoupler: advancedCouplerControl
  frontBypass: bypassDampers
  frontLockControl: driveModes
  gauge: gauges/genericGauges
  gauges/customModules/combustionEngineData: gauges/customModules/combustionEngineData
  gauges/customModules/environmentData: gauges/customModules/environmentData
  gtState0: xlab/gtState
  rangeboxControl: driveModes
  rearBypass: bypassDampers
  singleAxisLever: propAnimation/singleAxisLever
  transfercaseControl: driveModes
  twoStepLaunch: twoStepLaunch
  utv_naviscreen_accessory: beamNavigator
  vehicleController: vehicleController/vehicleController
