# Simulator configuration
beamng:
  host: 127.0.0.1
  port: 25252
  open_args:
    launch: False
    debug: False
    extensions:
      - xlab/xlabCore
  setup_funcs:
    beamng.settings.set_deterministic:
      steps_per_second: 0
    beamng.ui.show_hud: {}

# content/vehicles/
# "default_vehicle" - The standard datablock for vehicles (static or dynamic)
# "simple_object" - For basic physics objects
# "static_object" - For completely static, non-interactive objects
# "dynamic_object" - For physics-enabled interactive objects

# "BeamNGVehicle" - For any vehicle-based object (both drivable vehicles and static vehicle props)
# "TSStatic" - For static mesh objects that don't have physics
# "DecalRoad" - For road objects
# "TerrainBlock" - For terrain objects

# Scenario configuration
scenario:
  level: tech_ground # derby # Utah # tech_ground # tech_ground # smallgrid
  name: basic
  # # Additional objects to the scenario
  # extra_objects:
  #   sawhorse: # Descriptive name
  #     type: ScenarioObject
  #     oid: etk_test           # Unique object ID
  #     otype: BeamNGVehicle  # Object type - important!
  #     pos: [-3, -125, 0]
  #     rot:                  # Will be converted to a quaternion
  #       yaw_angle: 0
  #     scale: [1, 1, 1]
  #     JBeam: etk800     # Vehicle model name
  #     datablock: default_vehicle

  #   sawhorseT: # Descriptive name
  #     type: ScenarioObject
  #     oid: etk_tt           # Unique object ID
  #     otype: BeamNGVehicle  # Object type - important!
  #     pos: [0, -125, 0]
  #     rot:                  # Will be converted to a quaternion
  #       yaw_angle: 0
  #     scale: [1, 1, 1]
  #     JBeam: etk800     # Vehicle model name
  #     datablock: default_vehicle
  
  #   sawhorseN: # Descriptive name
  #     type: ScenarioObject
  #     oid: etk_t           # Unique object ID
  #     otype: BeamNGVehicle  # Object type - important!
  #     pos: [-2.3, -175, 0]
  #     rot:                  # Will be converted to a quaternion
  #       yaw_angle: 0
  #     scale: [1, 1, 1]
  #     JBeam: etk800     # Vehicle model name
  #     datablock: default_vehicle

  #   sawhorsett: # Descriptive name
  #     type: ScenarioObject
  #     oid: etk_ttt           # Unique object ID
  #     otype: BeamNGVehicle  # Object type - important!
  #     pos: [-6.3, -175, 0]
  #     rot:                  # Will be converted to a quaternion
  #       yaw_angle: 0
  #     scale: [1, 1, 1]
  #     JBeam: etk800     # Vehicle model name
  #     datablock: default_vehicle

  # extra_objects:
  #   cone0:
  #     JBeam: cones
  #     datablock: default_vehicle
  #     oid: cone0
  #     otype: BeamNGVehicle
  #     pos:
  #     - -6.0
  #     - -3.6739403974420594e-16
  #     - 0.0
  #     rot:
  #       yaw_angle: 0.0
  #     scale:
  #     - 1.0
  #     - 1.0
  #     - 1.0
  #     type: ScenarioObject
  #   cone1:
  #     JBeam: cones
  #     datablock: default_vehicle
  #     oid: cone1
  #     otype: BeamNGVehicle
  #     pos:
  #     - -5.999999999999999
  #     - -20.0
  #     - 0.0
  #     rot:
  #       yaw_angle: 0.0
  #     scale:
  #     - 1.0
  #     - 1.0
  #     - 1.0
  #     type: ScenarioObject
  #   cone10:
  #     JBeam: cones
  #     datablock: default_vehicle
  #     oid: cone10
  #     otype: BeamNGVehicle
  #     pos:
  #     - 47.26114814429711
  #     - 30.852227969682442
  #     - 0.0
  #     rot:
  #       yaw_angle: 0.0
  #     scale:
  #     - 1.0
  #     - 1.0
  #     - 1.0
  #     type: ScenarioObject
  #   cone11:
  #     JBeam: cones
  #     datablock: default_vehicle
  #     oid: cone11
  #     otype: BeamNGVehicle
  #     pos:
  #     - 46.66539374398922
  #     - 51.57671883944455
  #     - 0.0
  #     rot:
  #       yaw_angle: 0.0
  #     scale:
  #     - 1.0
  #     - 1.0
  #     - 1.0
  #     type: ScenarioObject
  #   cone12:
  #     JBeam: cones
  #     datablock: default_vehicle
  #     oid: cone12
  #     otype: BeamNGVehicle
  #     pos:
  #     - 37.196812500218115
  #     - 73.10254383166539
  #     - 0.0
  #     rot:
  #       yaw_angle: 0.0
  #     scale:
  #     - 1.0
  #     - 1.0
  #     - 1.0
  #     type: ScenarioObject
  #   cone13:
  #     JBeam: cones
  #     datablock: default_vehicle
  #     oid: cone13
  #     otype: BeamNGVehicle
  #     pos:
  #     - 12.354493316584058
  #     - 78.67005552430427
  #     - 0.0
  #     rot:
  #       yaw_angle: 0.0
  #     scale:
  #     - 1.0
  #     - 1.0
  #     - 1.0
  #     type: ScenarioObject
  #   cone14:
  #     JBeam: cones
  #     datablock: default_vehicle
  #     oid: cone14
  #     otype: BeamNGVehicle
  #     pos:
  #     - -3.5738628675184207
  #     - 60.12380162542953
  #     - 0.0
  #     rot:
  #       yaw_angle: 0.0
  #     scale:
  #     - 1.0
  #     - 1.0
  #     - 1.0
  #     type: ScenarioObject
  #   cone15:
  #     JBeam: cones
  #     datablock: default_vehicle
  #     oid: cone15
  #     otype: BeamNGVehicle
  #     pos:
  #     - -5.9998399317274655
  #     - 38.49896736027963
  #     - 0.0
  #     rot:
  #       yaw_angle: 0.0
  #     scale:
  #     - 1.0
  #     - 1.0
  #     - 1.0
  #     type: ScenarioObject
  #   cone2:
  #     JBeam: cones
  #     datablock: default_vehicle
  #     oid: cone2
  #     otype: BeamNGVehicle
  #     pos:
  #     - -5.996248918825451
  #     - -40.02657740037402
  #     - 0.0
  #     rot:
  #       yaw_angle: 0.0
  #     scale:
  #     - 1.0
  #     - 1.0
  #     - 1.0
  #     type: ScenarioObject
  #   cone3:
  #     JBeam: cones
  #     datablock: default_vehicle
  #     oid: cone3
  #     otype: BeamNGVehicle
  #     pos:
  #     - -2.9509899476758483
  #     - -61.8192053553918
  #     - 0.0
  #     rot:
  #       yaw_angle: 0.0
  #     scale:
  #     - 1.0
  #     - 1.0
  #     - 1.0
  #     type: ScenarioObject
  #   cone4:
  #     JBeam: cones
  #     datablock: default_vehicle
  #     oid: cone4
  #     otype: BeamNGVehicle
  #     pos:
  #     - 14.404244515319574
  #     - -79.29066160679095
  #     - 0.0
  #     rot:
  #       yaw_angle: 0.0
  #     scale:
  #     - 1.0
  #     - 1.0
  #     - 1.0
  #     type: ScenarioObject
  #   cone5:
  #     JBeam: cones
  #     datablock: default_vehicle
  #     oid: cone5
  #     otype: BeamNGVehicle
  #     pos:
  #     - 38.58701441570929
  #     - -71.50020786335966
  #     - 0.0
  #     rot:
  #       yaw_angle: 0.0
  #     scale:
  #     - 1.0
  #     - 1.0
  #     - 1.0
  #     type: ScenarioObject
  #   cone6:
  #     JBeam: cones
  #     datablock: default_vehicle
  #     oid: cone6
  #     otype: BeamNGVehicle
  #     pos:
  #     - 46.860282773161146
  #     - -49.713143684908346
  #     - 0.0
  #     rot:
  #       yaw_angle: 0.0
  #     scale:
  #     - 1.0
  #     - 1.0
  #     - 1.0
  #     type: ScenarioObject
  #   cone7:
  #     JBeam: cones
  #     datablock: default_vehicle
  #     oid: cone7
  #     otype: BeamNGVehicle
  #     pos:
  #     - 47.26115471277826
  #     - -29.147772030317274
  #     - 0.0
  #     rot:
  #       yaw_angle: 0.0
  #     scale:
  #     - 1.0
  #     - 1.0
  #     - 1.0
  #     type: ScenarioObject
  #   cone8:
  #     JBeam: cones
  #     datablock: default_vehicle
  #     oid: cone8
  #     otype: BeamNGVehicle
  #     pos:
  #     - 47.261152523284544
  #     - -9.147772030317396
  #     - 0.0
  #     rot:
  #       yaw_angle: 0.0
  #     scale:
  #     - 1.0
  #     - 1.0
  #     - 1.0
  #     type: ScenarioObject
  #   cone9:
  #     JBeam: cones
  #     datablock: default_vehicle
  #     oid: cone9
  #     otype: BeamNGVehicle
  #     pos:
  #     - 47.26115033379083
  #     - 10.852227969682483
  #     - 0.0
  #     rot:
  #       yaw_angle: 0.0
  #     scale:
  #     - 1.0
  #     - 1.0
  #     - 1.0
  #     type: ScenarioObject
  #   cone_0:
  #     JBeam: cones
  #     datablock: default_vehicle
  #     oid: cone_0
  #     otype: BeamNGVehicle
  #     pos:
  #     - 7.0
  #     - 4.286263797015736e-16
  #     - 0.0
  #     rot:
  #       yaw_angle: 0.0
  #     scale:
  #     - 1.0
  #     - 1.0
  #     - 1.0
  #     type: ScenarioObject
  #   cone_1:
  #     JBeam: cones
  #     datablock: default_vehicle
  #     oid: cone_1
  #     otype: BeamNGVehicle
  #     pos:
  #     - 7.000000000000001
  #     - -20.0
  #     - 0.0
  #     rot:
  #       yaw_angle: 0.0
  #     scale:
  #     - 1.0
  #     - 1.0
  #     - 1.0
  #     type: ScenarioObject
  #   cone_10:
  #     JBeam: cones
  #     datablock: default_vehicle
  #     oid: cone_10
  #     otype: BeamNGVehicle
  #     pos:
  #     - 34.26114814429719
  #     - 30.85222654651153
  #     - 0.0
  #     rot:
  #       yaw_angle: 0.0
  #     scale:
  #     - 1.0
  #     - 1.0
  #     - 1.0
  #     type: ScenarioObject
  #   cone_11:
  #     JBeam: cones
  #     datablock: default_vehicle
  #     oid: cone_11
  #     otype: BeamNGVehicle
  #     pos:
  #     - 33.76600088034438
  #     - 49.962511991067124
  #     - 0.0
  #     rot:
  #       yaw_angle: 0.0
  #     scale:
  #     - 1.0
  #     - 1.0
  #     - 1.0
  #     type: ScenarioObject
  #   cone_12:
  #     JBeam: cones
  #     datablock: default_vehicle
  #     oid: cone_12
  #     otype: BeamNGVehicle
  #     pos:
  #     - 27.989684654517042
  #     - 63.92491903911062
  #     - 0.0
  #     rot:
  #       yaw_angle: 0.0
  #     scale:
  #     - 1.0
  #     - 1.0
  #     - 1.0
  #     type: ScenarioObject
  #   cone_13:
  #     JBeam: cones
  #     datablock: default_vehicle
  #     oid: cone_13
  #     otype: BeamNGVehicle
  #     pos:
  #     - 17.239974084669427
  #     - 66.62297796729203
  #     - 0.0
  #     rot:
  #       yaw_angle: 0.0
  #     scale:
  #     - 1.0
  #     - 1.0
  #     - 1.0
  #     type: ScenarioObject
  #   cone_14:
  #     JBeam: cones
  #     datablock: default_vehicle
  #     oid: cone_14
  #     otype: BeamNGVehicle
  #     pos:
  #     - 8.808434149640387
  #     - 56.16416520539548
  #     - 0.0
  #     rot:
  #       yaw_angle: 0.0
  #     scale:
  #     - 1.0
  #     - 1.0
  #     - 1.0
  #     type: ScenarioObject
  #   cone_15:
  #     JBeam: cones
  #     datablock: default_vehicle
  #     oid: cone_15
  #     otype: BeamNGVehicle
  #     pos:
  #     - 7.000157968363342
  #     - 38.49157833906067
  #     - 0.0
  #     rot:
  #       yaw_angle: 0.0
  #     scale:
  #     - 1.0
  #     - 1.0
  #     - 1.0
  #     type: ScenarioObject
  #   cone_2:
  #     JBeam: cones
  #     datablock: default_vehicle
  #     oid: cone_2
  #     otype: BeamNGVehicle
  #     pos:
  #     - 7.0036234929748655
  #     - -39.96898159399015
  #     - 0.0
  #     rot:
  #       yaw_angle: 0.0
  #     scale:
  #     - 1.0
  #     - 1.0
  #     - 1.0
  #     type: ScenarioObject
  #   cone_3:
  #     JBeam: cones
  #     datablock: default_vehicle
  #     oid: cone_3
  #     otype: BeamNGVehicle
  #     pos:
  #     - 9.22088048067738
  #     - -57.2535104164608
  #     - 0.0
  #     rot:
  #       yaw_angle: 0.0
  #     scale:
  #     - 1.0
  #     - 1.0
  #     - 1.0
  #     type: ScenarioObject
  #   cone_4:
  #     JBeam: cones
  #     datablock: default_vehicle
  #     oid: cone_4
  #     otype: BeamNGVehicle
  #     pos:
  #     - 18.126838645086366
  #     - -66.83504869754293
  #     - 0.0
  #     rot:
  #       yaw_angle: 0.0
  #     scale:
  #     - 1.0
  #     - 1.0
  #     - 1.0
  #     type: ScenarioObject
  #   cone_5:
  #     JBeam: cones
  #     datablock: default_vehicle
  #     oid: cone_5
  #     otype: BeamNGVehicle
  #     pos:
  #     - 28.728147884388953
  #     - -63.02655748600684
  #     - 0.0
  #     rot:
  #       yaw_angle: 0.0
  #     scale:
  #     - 1.0
  #     - 1.0
  #     - 1.0
  #     type: ScenarioObject
  #   cone_6:
  #     JBeam: cones
  #     datablock: default_vehicle
  #     oid: cone_6
  #     otype: BeamNGVehicle
  #     pos:
  #     - 33.92035461647313
  #     - -48.46484111751822
  #     - 0.0
  #     rot:
  #       yaw_angle: 0.0
  #     scale:
  #     - 1.0
  #     - 1.0
  #     - 1.0
  #     type: ScenarioObject
  #   cone_7:
  #     JBeam: cones
  #     datablock: default_vehicle
  #     oid: cone_7
  #     otype: BeamNGVehicle
  #     pos:
  #     - 34.261154712778335
  #     - -29.147773453488185
  #     - 0.0
  #     rot:
  #       yaw_angle: 0.0
  #     scale:
  #     - 1.0
  #     - 1.0
  #     - 1.0
  #     type: ScenarioObject
  #   cone_8:
  #     JBeam: cones
  #     datablock: default_vehicle
  #     oid: cone_8
  #     otype: BeamNGVehicle
  #     pos:
  #     - 34.26115252328462
  #     - -9.147773453488309
  #     - 0.0
  #     rot:
  #       yaw_angle: 0.0
  #     scale:
  #     - 1.0
  #     - 1.0
  #     - 1.0
  #     type: ScenarioObject
  #   cone_9:
  #     JBeam: cones
  #     datablock: default_vehicle
  #     oid: cone_9
  #     otype: BeamNGVehicle
  #     pos:
  #     - 34.26115033379091
  #     - 10.85222654651157
  #     - 0.0
  #     rot:
  #       yaw_angle: 0.0
  #     scale:
  #     - 1.0
  #     - 1.0
  #     - 1.0
  #     type: ScenarioObject




post_scenario: {}

# Vehicle configuration
vehicles:
  ego: # Name of the car
    model: utv
    partConfig: /vehicles/utv/wild.pc
    license: EGO
    scenario_args:
      pos: [0,0,0]
      yaw_angle: 0
      # pos: [1898.416,3264.380,180.369]
      # # # pos: [-922.15802,-929.867981,135.533997]
      # yaw_angle: 180.0
      # # rot_quat: [0, 0, 0, 1.0]
    sensors:
      gtstate:
        type: GtState
        # gfx_update_time: 0.1
        # physics_update_time: 0.004
        # num_physics_steps_for_gfx_save: 1
        gfx_update_time: 0.15
        physics_update_time: 0.004
        num_physics_steps_for_gfx_save: 2
    controllers:
      LowLevelController: # The python class used
        controllerType: nn_mpc # The lua controller used
        gtStateName: gtstate
        drivetrain:
          mode: 2 # 0 : realistic, 1 : realistic autoclutch, 2 : arcade, 3 : realistic automatic
          startGear: 2 # with cvt, 0 : neutral, 1 : park, 2 : drive
        calibration:
          controlMode : auto
          gtStateSendRate: 0.01
          # modelName: wheel_speed_v4.json
          ctrl_type: 1 # 0 : wrdot,fxr; 1 : ff torque
          # modelName: wheel_speed_wit_integ_v1.json
          modelName: arata_torque_inverter.json
          TorqueKp: -0.21040940284729004
          TorqueKd: -0.000756041263230145
          TorqueKi: -20.635147094726562
          steeringKi: 0.1
          steeringKp: 0.01
          steeringToInput: -0.5948683325943701
          steeringIntegAlpha: 0.9 # 0.9
          commandTimeout: 1.0 # Timeout between two mpc solutions before giving back control
          ffcoef: 0.8
  # bolide: # Name of the car
  #   model: bolide
  #   # partConfig: /vehicles/utv/wild.pc
  #   license: EGO
  #   scenario_args:
  #     pos: [94.8773766,-53.2508202,23.1649094] # [50,0,0]
  #     yaw_angle: 0

# ROS configuration
ros_poll_config:
  ego:
    gtstate:
      topic: /ego/gtstate
      poll_time: 0.15
      publish: 1


# high_level_controller:
#   # # Check ipopt_rt_optimizer for the different fields and default values.
#   # num_stages: 21             # (int) Number of prediction stages (default: 20)
#   # delta_s:                   # (float or dict) Horizon step size(s)
#   #   base_ds: 1              # (float) Base step size (default: 0.5)
#   #   n_base: 10               # (int) Number of base steps (default: 15)
#   #   long_ds: 1.0             # (float) Long step size (default: 0.5)

#   # # Check ipopt_rt_optimizer for the different fields and default values.
#   # num_stages: 70             # (int) Number of prediction stages (default: 20)
#   # delta_s:                   # (float or dict) Horizon step size(s)
#   #   base_ds: 1.0              # (float) Base step size (default: 0.5)
#   #   n_base: 10               # (int) Number of base steps (default: 15)
#   #   long_ds: 1             # (float) Long step size (default: 0.5)

#   # Check ipopt_rt_optimizer for the different fields and default values.
#   num_stages: 21             # (int) Number of prediction stages (default: 20)
#   delta_s:                   # (float or dict) Horizon step size(s)
#     base_ds: 1.0              # (float) Base step size (default: 0.5)
#     n_base: 10               # (int) Number of base steps (default: 15)
#     long_ds: 1             # (float) Long step size (default: 0.5)

#   # # Q: State weighting (diag/cross-terms possible)
#   # Q:
#   #   e: 0.2
#   #   dphi: 3.0
#   #   beta: 5.0
#   #   wr: 0.2
#   #   delta: 0.1
#   #   # eng_tor: 0.1
#   #   throttle: 0.1

#   # # R: Control weighting
#   # R:
#   #   # delta_r: 0.05
#   #   # eng_tor_r: 0.1
#   #   delta_r: 1
#   #   # eng_tor_r: 0.1
#   #   throttle_r: 1.0

#   # # Q_t: Terminal state weighting
#   # Q_t:
#   #   e: 5
#   #   dphi: 10.0
#   #   beta: 10.0
#   #   wr: 1.0
#   #   delta: 0.1
#   #   V: 1.0
#   #   r: 1.0
#   #   # eng_tor: 

#   # Q: State weighting (diag/cross-terms possible)
#   Q:
#     e: 10
#     dphi: 100.0
#     beta: 100.0
#     wr: 5000
#     delta: 100
#     eng_tor: 100
#     # V: 100
#     # r: 100

#   # R: Control weighting
#   R:
#     # delta_r: 100
#     # eng_tor_r: 10
#     delta_r: 10
#     eng_tor_r: 10

#   # Q_t: Terminal state weighting
#   Q_t:
#     e: 10
#     dphi: 1000
#     beta: 1000
#     wr: 1000
#     delta: 1000
#     # V: 1000.0
#     # r: 1000.0
#     eng_tor: 1000

#   # x_range: state name -> [lb, ub]
#   x_range:
#     # e: [-4.0, 4.0]     # (float list) Lateral error range
#     e: [-50.0, 50.0]     # (float list) Lateral error range
  
#   # Reference path -> TODO: Proper path structure
#   # reference_traj: optimal_trajectory_v2.csv
#   reference_traj: fuji_full_state_optimal_trajectory_wheel.csv