# Simulator configuration
beamng:
  host: 127.0.0.1
  port: 25252
  open_args:
    launch: False
    debug: False
    extensions:
      - xlab/xlabCore
  setup_funcs:
    beamng.settings.set_deterministic:
      steps_per_second: 0
    beamng.ui.show_hud: {}

# Scenario configuration
scenario:
  level: smallgrid
  name: nn

post_scenario: {}

# Vehicle configuration
vehicles:
  ego: # Name of the car
    model: utv
    partConfig: /vehicles/utv/wild.pc
    license: EGO
    scenario_args:
      pos: [0,0,0]
      yaw_angle: 0
    sensors:
      gtstate:
        type: GtState
        gfx_update_time: 0.15
        physics_update_time: 0.005
        num_physics_steps_for_gfx_save: 1
    controllers:
      LowLevelController: # The python class used
        controllerType: nn # The lua controller used
        controllerRate: 0.005
        gtStateName: gtstate
        drivetrain:
          mode: 1 # 0 : realistic, 1 : realistic autoclutch, 2 : arcade, 3 : realistic automatic
          startGear: 2 # with cvt, 0 : neutral, 1 : park, 2 : drive


high_level_controller:
  control_fn: core://test_wheel_speed:compute_test_wheel_speed # The controller implementation
  control_rate: 0.01

# ROS configuration
ros_poll_config:
  ego:
    gtstate:
      topic: /ego/gtstate
      poll_time: 0.15
      publish: 1
