# Simulator configuration
beamng:
  host: 127.0.0.1
  port: 25252
  open_args:
    launch: False
    debug: False
    extensions:
      - xlab/xlabCore
  setup_funcs:
    beamng.settings.set_deterministic:
      steps_per_second: 0
    beamng.ui.show_hud: {}

# Scenario configuration
scenario:
  level: tech_ground
  name: path_follow

post_scenario: {}

# Vehicle configuration
vehicles:
  ego: # Name of the car
    model: utv
    partConfig: /vehicles/utv/wild.pc
    license: EGO
    scenario_args:
      pos: [0, 0, 0]
      yaw_angle: 0
    sensors:
      gtstate:
        type: GtState
        gfx_update_time: 0.15
        physics_update_time: 0.005
        num_physics_steps_for_gfx_save: 1
    controllers:
      LowLevelController: # The python class used
        controllerType: steer_basic # The lua controller used
        controllerRate: 0.005
        listenIp: 127.0.0.1
        listenPort: 64257
        sendIp: 127.0.0.1
        sendPort: 64258
        gtStateName: gtstate
        calibration:
          maxSteeringAngle: 0.69
          Kp_speed: 0.2
          wheelbase: 2.58

high_level_controller:
  control_fn: core://path_follow:compute_control
  control_rate: 0.01
  pp_lookahead: 6
  pp_lookahead_gain: 0.4
  stanley_k: 0.7
  lookahead_distances_pct: [0.4, 0.8, 1.2]
  desired_speed: 5.0
  path_file: loop_700_500_30_50_1-2_20.csv
  max_steer_rad: 0.69
  wheelbase: 2.58

# ROS configuration
ros_poll_config:
  ego:
    gtstate:
      topic: /ego/gtstate
      poll_time: 0.15
      publish: 1
