# Copy of pure_pursuit.yaml with the EGO vehicle set to ETK800 (844_track_M)

# Simulator configuration
beamng:
  open_args:
    launch: False
    debug: False
    extensions:
      - xlab/xlabCore
  setup_funcs:
    beamng.settings.set_deterministic:
      # -1: Run 1000/fpslimit ms of physics per frame
      # 0: Simulate physics time based on wallclock delta to the last frame
      # n: Simulate n * 50ms of physics per frame (for any positive n)
      steps_per_second: 0
    beamng.ui.show_hud: {}

# Level configuration (new schema)
scenario:
  level: derby  # Level to load in CREATE mode
  name: basic  # Optional objects to spawn

scenario_mode: create

extra_objects: {}  # Optional objects to spawn

# Vehicle configuration
vehicles:
  EGO: # Name of the car
    model_args:
      model: etk800
      part_config: /vehicles/etk800/844_track_M.pc
      license: EGO
    spawn:
      pos: [-0.243, 148.0445, 79.3]
      yaw_angle: -90.0
      cling: True
    sensors:
      basicState:
        type: BasicState
      gtstate:
        type: GtState
        gfx_update_time: 0.3
        physics_update_time: 0.005
        num_physics_steps_for_gfx_save: 1
        # Filter parameters for the estimator
        kf_predict_gain: 0.85
        accel_tau_s: 0.04
        gyro_tau_s: 0.005
        vel_tau_s: 0.005
        wheel_angvel_tau_s: 0.005
        debug_raw: True
    controllers:
      LowLevelController: # The python setup class used
        controllerType: nn_torque
        controllerRate: 0.01
        gtStateName: gtstate
        gtStateSendRate: 0.01
        drivetrain:
          mode: 2 # 0 : realistic, 1 : realistic autoclutch, 2 : arcade, 3 : realistic automatic
          # startGear: 0 # with cvt, 0 : neutral, 1 : park, 2 : drive
          disableSafety: True # Disable safety features like ESC, ABS, TCS, etc. if enabled
        calibration:
          controlMode : auto
          # Speed controller parameters
          speed_c0: 0
          speed_c1: 0
          speed_c2: 0
          speed_c3: 0
          speed_c4: 0
          speedKp: 0
          speedKi: 0

# ROS configuration
ros_poll_config:
  EGO:
    basicState:
      poll_time: 0.2
      publish: True
    gtstate:
      poll_time: 0.25
      publish: 1
