# Example of a basic scenario configuration file for initiatin beamng sim

# Simulator configuration
beamng:
  open_args:
    launch: False
    debug: False
    extensions:
      - xlab/xlabCore
  setup_funcs:
    beamng.settings.set_deterministic:
      # -1: Run 1000/fpslimit ms of physics per frame
      # 0: Simulate physics time based on wallclock delta to the last frame
      # n: Simulate n * 50ms of physics per frame (for any positive n)
      steps_per_second: 0
    beamng.ui.show_hud: {}

# Level configuration (new schema)
scenario:
  # level: smallgrid  # Level to load in CREATE mode
  level: derby  # Level to load in CREATE mode
  name: basic  # Optional objects to spawn

scenario_mode: create

extra_objects: {}  # Optional objects to spawn

# post_scenario: {}

# Vehicle configuration
vehicles:
  EGO: # Name of the car
    model_args:
      # model: sunburst2 # bolide # utv # etk800 # utv # bolide, etk800, wild (utv)
      # part_config: /vehicles/sunburst2/drift_pro.pc
      model: utv # bolide # utv # etk800 # utv # bolide, etk800, wild (utv)
      part_config: /vehicles/utv/wild.pc
      # model: etk800 # bolide # utv # etk800 # utv # bolide, etk800, wild (utv)
      # part_config: vehicles/etk800/844_track_M.pc
      license: EGO
    spawn:  # Renamed from scenario_args
      # # pos: [0, 0, 0]
      # pos: [44.05, 127.22, 79.3]
      pos: [-0.243, 148.0445, 79.3]
      yaw_angle: -90.0
      cling: True  # Ground snapping
    # All the sensors that the vehicle has
    sensors:
      # gps:
      #   type: GPS
      #   pos: [0, 0, 0]
      #   gfx_update_time: 0.0
      #   physics_update_time: 0.01
      #   ref_lon: 0
      #   ref_lat: 0
      # electrics:
      #   type: Electrics
      basicState:
        type: BasicState
      # # imu:
      # #   type: AdvancedIMU
      # #   gfx_update_time: 0.05
      # #   physics_update_time: 0.01
      # #   is_using_gravity: True
      # #   is_visualised: True
      # #   is_dir_world_space: False
      # #   # Up and dir name are confusing, but it is the way it is
      # #   dir: [0, -1, 0] # First axis
      # #   up: [1, 0, 0] # Second axis in right hand rule
      # #   pos: [0, 0, 3]
      gtstate:
        type: GtState
        gfx_update_time: 0.3
        physics_update_time: 0.005
        num_physics_steps_for_gfx_save: 5
        torqueNN:
          modelName: arata_torque_map.json   # resolves under lua/vehicle/controller/xlab/models/
          outputScaling: 100.0               # ONLY scaling used by gtState
          fieldName: rear_wheel_torque_est        # optional (default: estimated_torque)
        # pos: [0, 0, 3] # Position is relative to the center of mass of the vehicle
        # pos: cog # Position could be a string: 'cog, 'front', 'rear', 'left', 'right'.
        # is_pos_relative_to_cog: True
        # use_reference_info: True
        # is_visualised: True
        # is_dir_world_space: False
        # # Up and dir name are confusing, but it is the way it is
        # dir: [0, -1, 0] # First axis
        # up: [1, 0, 0] # Second axis in right hand rule
    controllers:
      LowLevelController: # The python setup class used
        controllerType: nn_torque
        controllerRate: 0.01
        gtStateName: gtstate
        gtStateSendRate: 0.01
        drivetrain:
          mode: 2 # 0 : realistic, 1 : realistic autoclutch, 2 : arcade, 3 : realistic automatic
          startGear: 2 # with cvt, 0 : neutral, 1 : park, 2 : drive
        calibration:
          controlMode : auto
          # gtStateSendRate: 0.01
          # modelName: wheel_speed_v4.json
          # ctrl_type: 1 # 0 : wrdot,fxr; 1 : ff torque
          # modelName: wheel_speed_wit_integ_v1.json
          modelName: arata_torque_inverter.json
          TorqueKp: -0.21040940284729004
          TorqueKd: -0.000756041263230145
          TorqueKi: -20.635147094726562
          steeringKi: 0.1
          steeringKp: 0.01
          steeringToInput: -0.5948683325943701
          steeringIntegAlpha: 0.9 # 0.9
          commandTimeout: 3.0 # Timeout between two mpc solutions before giving back control
          ffcoef: 0.8
          vel_time_scale: 0.1


# high_level_controller:
#   control_fn: core://test_patterns:compute_control_multi_test # The controller implementation
#   control_rate: 0.01

# ROS configuration
ros_poll_config:
  EGO:
    basicState:
      # topic: /ego/basicState
      poll_time: 0.1
      publish: True
    gtstate:
      # topic: /ego/gtstate
      poll_time: 0.25 # Make sure this matches the gfx_update_time and is not 3 times slower
      publish: 1 # 0 is false, 1 is true, 2 is true and publish to all
      # publish_all: True
