# Simulator configuration
beamng:
  host: 127.0.0.1
  port: 25252
  open_args:
    launch: False
    debug: False
    extensions:
      - xlab/xlabCore
  setup_funcs:
    beamng.settings.set_deterministic:
      steps_per_second: 60
    beamng.ui.show_hud: {}

# Scenario configuration
scenario:
  level: tech_ground
  name: basic

post_scenario: {}

# Vehicle configuration
vehicles:
  ego: # Name of the car
    model: utv
    partConfig: /vehicles/utv/wild.pc
    license: EGO
    scenario_args:
      pos: [0,0,0]
      yaw_angle: 0
    sensors:
      gtstate:
        type: GtState
        gfx_update_time: 0.15
        physics_update_time: 0.005
        num_physics_steps_for_gfx_save: 1
    controllers:
      LowLevelController: # The python class used
        controllerType: nn # The lua controller used
        controllerRate: 0.005
        listenIp: 127.0.0.1
        listenPort: 64257
        sendIp: 127.0.0.1
        sendPort: 64258
        gtStateName: gtstate
        calibration:
          maxSteeringAngle : 40 # has to be obtained manually
          throttleP : 0.2
          throttleI : 0.000
          throttleD : 0.000


high_level_controller:
  control_fn: compute_control_pid # The C function used
  control_rate: 0.01

# ROS configuration
ros_poll_config:
  ego:
    gtstate:
      topic: /ego/gtstate
      poll_time: 0.15
      publish: 1
