/* Auto-generated by mcu_export.py — do not edit. */
#ifndef DRIVETRAIN_MAPS_H
#define DRIVETRAIN_MAPS_H

#ifdef __cplusplus
extern "C" {
#endif

float drivetrain_inverse_throttle(float engine_speed_rads, float boost_pressure, float rear_wheelspeed_ms, float torque_cmd);
float drivetrain_forward_torque(float engine_speed_rads, float boost_pressure, float rear_wheelspeed_ms, float throttle_cmd);

extern const float drivetrain_wheel_gain;

#ifdef __cplusplus
}
#endif

#endif /* DRIVETRAIN_MAPS_H */
