drift:
  args:
    boost_config:
      args:
        activation_fn: tanh
        fake_normalization: true
        initial_value_range: 0.1
        layers_archictecture: !!python/tuple
        - 64
        - 64
      type: MLP
    gear_ratio_config:
      args:
        activation_fn: tanh
        initial_value_range: 0.01
        layers_archictecture: !!python/tuple
        - 32
        - 32
      type: MLP
    guided_parameters: {}
    latent_config:
      gear_dynamic:
        args:
          activation_fn: tanh
          fake_normalization: true
          initial_value_range: 0.01
          layers_archictecture: !!python/tuple
          - 32
          - 32
        type: MLP
    net_torque_config:
      engine:
        args:
          activation_fn: tanh
          fake_normalization: true
          initial_value_range: 0.1
          layers_archictecture: !!python/tuple
          - 128
          - 128
        type: MLP
      res_wheelspeed:
        args:
          activation_fn: tanh
          initial_value_range: 0.1
          layers_archictecture: !!python/tuple
          - 32
          - 32
        type: MLP
      shaft:
        args:
          activation_fn: tanh
          fake_normalization: true
          initial_value_range: 0.1
          layers_archictecture: !!python/tuple
          - 32
          - 32
        type: MLP
    state_action_mean:
      boost_pressure: 0.5267380784049059
      engine_speed: 61.8203063431727
      rear_wheelspeed: 4.9722713347946605
      throttle: 0.29450363136256685
      time: 99.51250472659012
    state_action_std:
      boost_pressure: 0.8857709612550487
      engine_speed: 11.38578108883205
      rear_wheelspeed: 1.9278908348520307
      throttle: 0.3591534820571994
      time: 23.30921913348017
    state_max_min:
      boost_pressure:
        max: 3.080124661928808
        min: -1.3480898303199045
      engine_speed:
        max: 84.85595975941035
        min: 13.4126580418111
      rear_wheelspeed:
        max: 9.922488727156553
        min: -0.49680832133755826
      throttle:
        max: 2.0
        min: -1.0
      time:
        max: 140.88250664406
        min: 58.142502809118
    stop_gradient: true
    use_normalized_input: true
  type: ImprovedEngineDynamics
noise:
  args:
    ignore_noise: false
    max_noise:
    - 1.0
    - 0.30000001192092896
    - 0.30000001192092896
    noise_network_config:
      args:
        activation_fn: tanh
        initial_value_range: 0.1
        layers_archictecture: !!python/tuple
        - 64
        - 64
      type: MLP
    output_dimension: 3
  type: NNNoiseTerm
